name: Scrape latest news releases

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '12 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Pull Node packages
      run: |-
        cd scripts
        npm install
    - name: Fetch latest data
      run: |-
        node scripts/update-announcement-urls.js
    - name: Commit and push if it changed
      run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data/source/urls-news-releases.json
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
